service: waf-authorizer

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:env}
  region: ${opt:region}
  timeout: 20
  deploymentBucket:
    name: ${opt:bucket}
  environment:
    APP_ENV: ${self:provider.stage}
    AUTH_TIMEOUT_HOURS: 4
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    WAF_IPSET: ${self:service}-${self:provider.stage}
    WEB_FRONTEND: ${opt:frontend}
  apiKeys:
    - ${self:service}-${self:provider.stage}

plugins:
  - serverless-domain-manager
  - serverless-plugin-scripts

custom:
  customDomain:
    enabled: true
    domainName: ${opt:domain}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  scripts:
    hooks:
      'deploy:initialize': make build

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  redirect:
    handler: bin/redirect
    events:
      - http:
          path: /
          method: get
  generate:
    handler: bin/generate
    role: lambdaRole
    events:
      - http:
          path: /generate
          method: post
          private: true
  allowlist:
    handler: bin/allowlist
    role: lambdaRole
    events:
      - http:
          path: /allowlist/{path+} 
          method: get
  cleanup:
    handler: bin/cleanup
    role: lambdaRole
    events:
      - schedule: rate(5 minutes)

resources:
  Resources:
    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-lambda
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${self:provider.stage}-lambda
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: 
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource: 
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:dynamodb'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'table/${self:provider.environment.DYNAMODB_TABLE}'
                - Effect: Allow
                  Action:
                    - waf:GetChangeToken
                  Resource: 
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:waf:'
                        - Ref: 'AWS::AccountId'
                        - 'changetoken/*'
                - Effect: Allow
                  Action:
                    - waf:ListIPSets
                    - waf:UpdateIPSet
                  Resource: 
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:waf:'
                        - Ref: 'AWS::AccountId'
                        - 'ipset/*'
    allowlistTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: AccessCode
            AttributeType: S
        KeySchema:
          - AttributeName: AccessCode
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5